apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: my-app
