name: CI/CD Pipeline
#skadlakdsakl
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            bilsyp/my-app-ndn:${{ github.sha }}
            bilsyp/my-app-ndn:latest
          cache-from: type=registry,ref=bilsyp/my-app-ndn:latest
          cache-to: type=inline

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to Kubernetes
        run: |
          # Apply Kubernetes manifests
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          # Update ke image terbaru
          kubectl set image deployment/my-app my-app=bilsyp/my-app-ndn:${{ github.sha }} -n my-app

          # Tunggu sampai deployment selesai
          if ! kubectl rollout status deployment/my-app -n my-app --timeout=300s; then
            echo "Deployment failed to roll out"
            kubectl rollout undo deployment/my-app -n my-app
            exit 1
          fi
